services:
  - type: web
    name: forex-analysis-pro
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1
    plan: free
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    scaling:
      minInstances: 1
      maxInstances: 1
